version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: D@£^dJSsu*S)kl&J9Dsk
